/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.prog2.labs;

import java.util.Map;

/**
 *
 * @author Admin
 */
public class viewLibrarian extends javax.swing.JFrame {

    /**
     * Creates new form viewLibrarian
     */
    //Singleton
    LibraryController controller = LibraryController.getInstance();

    public viewLibrarian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newBook_btn = new javax.swing.JButton();
        issueABook_btn = new javax.swing.JButton();
        returnBook_btn = new javax.swing.JButton();
        allBooks_btn = new javax.swing.JButton();
        borrowedBooks_btn = new javax.swing.JButton();
        logOut_btn = new javax.swing.JButton();
        libName_lbl = new javax.swing.JLabel();
        langToggleBtn = new javax.swing.JToggleButton();
        vL_Heading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Librarian - Menu");

        newBook_btn.setText("Add New Book");
        newBook_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBook_btnActionPerformed(evt);
            }
        });

        issueABook_btn.setText("Issue a Book");
        issueABook_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueABook_btnActionPerformed(evt);
            }
        });

        returnBook_btn.setText("Return a Book");
        returnBook_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBook_btnActionPerformed(evt);
            }
        });

        allBooks_btn.setText("View All Books");
        allBooks_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBooks_btnActionPerformed(evt);
            }
        });

        borrowedBooks_btn.setText("Borrowed Books");
        borrowedBooks_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowedBooks_btnActionPerformed(evt);
            }
        });

        logOut_btn.setText("Log Out");
        logOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btnActionPerformed(evt);
            }
        });

        langToggleBtn.setText("FR");

        vL_Heading.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        vL_Heading.setText("WELCOME LIBRARIAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(libName_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(langToggleBtn)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(issueABook_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(borrowedBooks_btn)
                                    .addComponent(newBook_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(returnBook_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(logOut_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(allBooks_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(vL_Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(vL_Heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(libName_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBook_btn)
                    .addComponent(allBooks_btn))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrowedBooks_btn)
                    .addComponent(returnBook_btn))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueABook_btn)
                    .addComponent(logOut_btn))
                .addGap(36, 36, 36)
                .addComponent(langToggleBtn)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btnActionPerformed
        // TODO add your handling code here:
        logInLibrarian linl = new logInLibrarian();
        linl.show();
        this.dispose();
    }//GEN-LAST:event_logOut_btnActionPerformed

    private void allBooks_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBooks_btnActionPerformed
        // TODO add your handling code here:
        this.hide();
        String category = "All Books";

        //controller to dao
        Map<String, String> s = controller.viewAllBooks();

        viewAllBooks viewBooks = new viewAllBooks(category, s);
        viewBooks.setVisible(true);

    }//GEN-LAST:event_allBooks_btnActionPerformed

    private void newBook_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBook_btnActionPerformed
        // TODO add your handling code here:
        //addBook(String SN, String title, String author, String publisher, float price, int quantity, int issued)
    }//GEN-LAST:event_newBook_btnActionPerformed

    private void borrowedBooks_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowedBooks_btnActionPerformed
        // TODO add your handling code here:

        //displays all borrowed borrowed books
        //if issued > 1, display borrowed books
        this.hide();

        String category = "Borrowed Books";

         Map<String, String> s = controller.viewIssuedBooks();

        viewAllBooks viewBooks = new viewAllBooks(category, s);
        viewBooks.setVisible(true);

    }//GEN-LAST:event_borrowedBooks_btnActionPerformed

    private void issueABook_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueABook_btnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_issueABook_btnActionPerformed

    private void returnBook_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBook_btnActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_returnBook_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewLibrarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allBooks_btn;
    private javax.swing.JButton borrowedBooks_btn;
    private javax.swing.JButton issueABook_btn;
    private javax.swing.JToggleButton langToggleBtn;
    private javax.swing.JLabel libName_lbl;
    private javax.swing.JButton logOut_btn;
    private javax.swing.JButton newBook_btn;
    private javax.swing.JButton returnBook_btn;
    private javax.swing.JLabel vL_Heading;
    // End of variables declaration//GEN-END:variables
}
